In [1]:
import numpy as np

Temperature = np.array([60, 70, 80, 90, 100])
Customer = np.array([100, 150, 180, 190, 195])

In [2]:
Temperature

array([ 60,  70,  80,  90, 100])

In [3]:
Customer

array([100, 150, 180, 190, 195])

In [4]:
type(Temperature)

numpy.ndarray

In [5]:
type(Customer)

numpy.ndarray

In [8]:
Temperature.std()

14.142135623730951

In [7]:
np.mean(Temperature)

80.0

In [11]:
Temperature[4]

100

In [12]:
np.corrcoef(Temperature, Customer)

array([[1.        , 0.92519568],
       [0.92519568, 1.        ]])

In [17]:
TempCust = np.array([np.random.randint(50,100,20),np.random.randint(10,200,20)])

In [18]:
TempCust[1]

array([132, 186,  12, 166,  90, 191, 120, 154, 180, 136,  31,  23, 127,
       195, 119,  75, 118,  63, 108,  43])

In [19]:
TempCust[0]

array([54, 93, 83, 94, 69, 66, 84, 57, 60, 64, 64, 83, 75, 91, 70, 51, 83,
       83, 97, 80])